---
title: "XGBoost"
output: html_document
---

A very high performance gradient boosting model with decision trees implementation (therefore feature scaling is not needed).  Great for large datasets - even better than neural nets at times!

> You keep the interpretation of your data set since feature scaling is not needed!

```{r echo=FALSE, warning=FALSE, message=FALSE}
if(!require(easypackages)){install.packages("easypackages")}
library(easypackages)
packages("caTools", "xgboost", "caret", prompt = FALSE)
```

```{r}
# Importing the dataset
dataset = read.csv('../data/Churn_Modelling.csv')
dataset = dataset[4:14]

# Encoding the categorical variables as factors
dataset$Geography = as.numeric(factor(dataset$Geography,
        levels = c('France', 'Spain', 'Germany'), labels = c(1, 2, 3)))
dataset$Gender = as.numeric(factor(dataset$Gender,
          levels = c('Female', 'Male'), labels = c(1, 2)))

# Splitting the dataset into the Training set and Test set - caTools
set.seed(123)
split = sample.split(dataset$Exited, SplitRatio = 0.8)
training_set = subset(dataset, split == TRUE)
test_set = subset(dataset, split == FALSE)

# Fitting XGBoost to the Training set - xgboost
# There are lots of tuning parameters - Need to explore more thoroughly
classifier = xgboost(data = as.matrix(training_set[-11]), 
           label = training_set$Exited, nrounds = 10)
#nrounds is low since the data is pretty small and simple - 100 improves it to 0.195796

# Predicting the Test set results
y_pred = predict(classifier, newdata = as.matrix(test_set[-11]))
y_pred = (y_pred >= 0.5)

# Making the Confusion Matrix
cm = table(test_set[, 11], y_pred)
cm
cm = prop.table(table(test_set[, 11], y_pred))
cm

# Applying k-Fold Cross Validation - caret
folds = createFolds(training_set$Exited, k = 10)
cv = lapply(folds, function(x) {
  training_fold = training_set[-x, ]
  test_fold = training_set[x, ]
  classifier = xgboost(data = as.matrix(training_set[-11]), label = training_set$Exited, nrounds = 10)
  y_pred = predict(classifier, newdata = as.matrix(test_fold[-11]))#this gives probabilities
  y_pred = (y_pred >= 0.5)#convert probabilities to 0/1
  cm = table(test_fold[, 11], y_pred)
  accuracy = (cm[1,1] + cm[2,2]) / (cm[1,1] + cm[2,2] + cm[1,2] + cm[2,1])
  return(accuracy)
})
accuracy = mean(as.numeric(cv))
accuracy
```

Beats the accuracy of ANN!
